name: 🧱 Build DLL & release (Windows)

env:
    PLUGIN_NAME: CustomBallOnline
    PLUGIN_NAME_FORMATTED: Custom Ball Online
    TAG_NAME: ${{ github.event.inputs.tag || github.ref_name }}

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:
        inputs:
            tag:
                description: "Release tag (e.g. v1.0.1)"
                required: true
permissions:
    contents: write

jobs:
    check-changelog:
        name: Check changelog (main)
        runs-on: windows-latest
        outputs:
            changelog: ${{ steps.changelog.outputs.changelog }}
        steps:
            - name: 📥 Checkout repository (main)
              uses: actions/checkout@v4
              with:
                  ref: main
                  submodules: false

            - name: 📝 Extract changes from changelog
              id: changelog
              shell: bash
              run: |
                  # Prefer manual input if available
                  TAG="${{ github.event.inputs.tag || github.ref_name }}"

                  # fail if tag not found in CHANGELOG.md
                  if ! grep -q "^## $TAG" CHANGELOG.md; then
                    echo "❌ Tag '$TAG' not found in CHANGELOG.md"
                    exit 1
                  fi

                  echo "Using tag: $TAG"

                  NOTES=$(awk "/^## $TAG/{flag=1; next} /^## /{flag=0} flag" CHANGELOG.md)

                  echo "Extracted notes:"
                  echo "$NOTES"

                  {
                    echo "changelog<<EOF"
                    echo "$NOTES"
                    echo "EOF"
                  } >> "$GITHUB_OUTPUT"

    build:
        name: Build holy version (main)
        needs: check-changelog
        uses: ./.github/workflows/build-template.yml
        with:
            branch: main
            artifact_suffix: ""

    build-ac-version:
        name: Build inferior version (ac-version)
        needs: check-changelog
        uses: ./.github/workflows/build-template.yml
        with:
            branch: ac-version
            artifact_suffix: "-AC"

    release:
        needs: [check-changelog, build, build-ac-version]
        runs-on: windows-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: ./artifacts
                  merge-multiple: true # <--- FLATTENS all artifacts into ./artifacts

            - name: 🧪 Check downloaded artifacts
              shell: bash
              run: |
                  echo "Contents of artifacts folder:"
                  find artifacts -type f

            - name: 🚀 Create release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  body: |
                      ## Install Steps
                      1. Close Rocket League

                      2. Click `CustomBallOnline.zip` or `CustomBallOnline-AC.zip` below to download it
                          - `CustomBallOnline.zip` is a superior version for people who don't use AlphaConsole
                          - `CustomBallOnline-AC.zip` is for people who use AlphaConsole

                      3. Extract the `.zip` file and run `install.bat`
                            <details> <summary>Getting an error when running <code>install.bat</code> ?</summary>
                                <ul><br>
                                    <li>Drag/drop <code>${{ env.PLUGIN_NAME }}.dll</code> into your bakkesmod plugins folder, usually located here:
                                    <br><code>C:\Users\{YOUR USERNAME}\AppData\Roaming\bakkesmod\bakkesmod\plugins</code></li>
                                </ul>
                            </details>

                      ## Notes
                      ${{ needs.check-changelog.outputs.changelog }}
                  files: artifacts/*.zip

            - name: 🤓 Post release info in discord channel
              uses: sarisia/actions-status-discord@v1
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  nodetail: true
                  title: "**${{ env.PLUGIN_NAME_FORMATTED }}** `${{ env.TAG_NAME }}` has been released! ⚽ 🚀"
                  description: |
                      ### Notes
                      ${{ needs.check-changelog.outputs.changelog }}

                      **Download:** [${{ env.TAG_NAME }}](${{ steps.create_release.outputs.url }})
                  color: 0xA81CFF
